#!/usr/bin/env node
// Generated by the claude-rules plugin. Do not edit.
// Verifies that vendored rules still match .claude/rules-lock.json.
// Regenerate with /claude-rules:update — never by hand.
import { createHash } from "node:crypto";
import { readFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const claudeDir = dirname(fileURLToPath(import.meta.url));
const projectRoot = resolve(claudeDir, "..");
const lockPath = join(projectRoot, ".claude/rules-lock.json");

const digest = (contents) =>
  "sha256-" +
  createHash("sha256").update(contents.replace(/\r\n/g, "\n")).digest("hex");

const lockRaw = await readFile(lockPath, "utf8").catch(() => null);
if (lockRaw === null) {
  console.error("rules-check: .claude/rules-lock.json not found — run /claude-rules:update");
  process.exit(1);
}

const lock = JSON.parse(lockRaw);
const missing = [];
const modified = [];

for (const [relativePath, expected] of Object.entries(lock.files ?? {})) {
  const contents = await readFile(join(projectRoot, relativePath), "utf8").catch(
    () => null,
  );
  if (contents === null) {
    missing.push(relativePath);
    continue;
  }
  if (digest(contents) !== expected) {
    modified.push(relativePath);
  }
}

if (missing.length === 0 && modified.length === 0) {
  const count = Object.keys(lock.files ?? {}).length;
  console.log(`rules-check: ${count} vendored files match ${lock.source}@${lock.version}`);
  process.exit(0);
}

console.error("rules-check: vendored rules do not match the lock.\n");
for (const path of missing) console.error(`  missing:  ${path}`);
for (const path of modified) console.error(`  modified: ${path}`);
console.error(
  "\nThese files are vendored from " +
    `${lock.source}. Do not edit them here — the change would be ` +
    "overwritten on the next sync and is invisible to every other repo.\n" +
    "Edit the rule upstream, release it, then run /claude-rules:update.\n" +
    "To discard local edits and restore the locked content, re-run the sync.",
);
process.exit(1);
